# Generated by Django 4.2.6 on 2023-10-24 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0002_exames_agendarexame'),
    ]

    operations = [
        migrations.AddField(
            model_name='exames',
            name='duracao',
            field=models.TimeField(default='00:00'),
        ),
    ]
