# Generated by Django 4.2.6 on 2023-11-18 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresarial', '0004_remove_procedimentos_agressividade_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procedimentos',
            name='outras',
        ),
        migrations.RemoveField(
            model_name='procedimentos',
            name='pontoT',
        ),
        migrations.AddField(
            model_name='procedimentos',
            name='outras',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='empresarial.outrasregioes'),
        ),
        migrations.AddField(
            model_name='procedimentos',
            name='pontoT',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='empresarial.pontostratados'),
        ),
    ]
