# Generated by Django 4.2.6 on 2023-11-18 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresarial', '0007_rename_torácica_procedimentos_toracica'),
    ]

    operations = [
        migrations.RenameField(
            model_name='procedimentos',
            old_name='Toracica',
            new_name='Torácica',
        ),
    ]
