# Generated by Django 4.2.6 on 2023-11-19 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresarial', '0008_rename_toracica_procedimentos_torácica'),
    ]

    operations = [
        migrations.CreateModel(
            name='Financeiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('novoGasto', models.CharField(max_length=300, null=True)),
                ('valorGasto', models.FloatField(null=True)),
                ('dataGasto', models.DateField(null=True)),
                ('recebidoExames', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='empresarial.procedimentos')),
            ],
        ),
        migrations.DeleteModel(
            name='OutrasRegioes',
        ),
        migrations.DeleteModel(
            name='PontosTratados',
        ),
    ]
