# Generated by Django 4.2.6 on 2023-11-19 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresarial', '0009_financeiro_delete_outrasregioes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gastos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('novoGasto', models.CharField(max_length=300, null=True)),
                ('valorGasto', models.FloatField(null=True)),
                ('dataGasto', models.DateField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Financeiro',
        ),
    ]
